# These are supported funding model platforms

github: Wumpuspro # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: Blazerop # Replace with a single Patreon username

